### ISSUE TITLE
OLEDthing.dll missing

### ISSUE THREAD

**Issue by mikecy22** [chilyashev/AfterburnerMonitor#1]
Hello. I am trying your program and when i press connect a popup error shows "Unable to load dll file "OLEDthing.dll". Is a file missing?

**Comment by chilyashev** [comment]
Hey, I know you've probably long forgotten about this and I'm sorry I didn't have time to see it.

Are you sure you're successfully building both projects in the solution? The OLEDThing project is the one creating the OLEDThing.dll file.

![image](https://user-images.githubusercontent.com/679183/35046432-a6cfedd0-fb9f-11e7-9cbc-978ff4797dea.png)
